eureka:
  client:
    service-url.defaultZone: "http://liyq:123@euk1.com:7001/eureka/"
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
  instance:
#    hostname: provider-server1
    appname: provider-server2
server:
  port: 81
spring:
  application:
    name: providerserver

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
