eureka:
  client:
    service-url.defaultZone: "http://euk1.com:7001/eureka/"
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true

  instance:
#    hostname: eureka-server1
    appname: eureka-server2
  server:
    enable-self-preservation: true
server:
  port: 7001
spring:
  application:
    name: eureka-server
  security:
    user:
      name: "liyq"
      password: "123"

management:
#  server:
#    port: 7071
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

