eureka:
  client:
    service-url.defaultZone: "http://euk1.com:7001/eureka/"
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
  instance:
#    hostname: eureka-server1
    appname: eureka-server2
server:
  port: 7002
spring:
  application:
    name: eureka-server

management:
#  server:
#    port: 7072
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
